version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - ./create-data.sql:/docker-entrypoint-initdb.d/create-data.sql
    ports:
      - "5432:5432"

# TODO добавить сервисы
  gateway:
    image: vhung98vp/gateway:1.1
    container_name: gateway
    build: ./gateway/
    ports:
      - "8080:8080"
    depends_on:
      - reservation
      - library
      - rating
    environment:
      RATING_URL: "http://rating:8050"
      LIBRARY_URL: "http://library:8060"
      RESERVATION_URL: "http://reservation:8070"
      
  reservation:
    image: vhung98vp/reservation:1.1
    container_name: reservation
    build: ./reservation/
    ports:
      - "8070:8070"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/reservations"
      GATEWAY_URL: "http://gateway:8080"      

  library:
    image: vhung98vp/library:1.1
    container_name: library
    build: ./library/
    ports:
      - "8060:8060"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/libraries"
      
  rating:
    image: vhung98vp/rating:1.1
    container_name: rating
    build: ./rating/
    ports:
      - "8050:8050"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/ratings"

volumes:
  db-data: