name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3.1
        id: install
      
      # TODO build, publish to docker hub, deploy to k8s
      - name: Build images
        run: docker-compose build

      # - name: Push images
      #   run: |
      #     docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #     docker-compose push

      - name: Create K8S config
        run: |
          mkdir $HOME/.kube
          echo ${{ secrets.K8S_CONFIG }} | base64 -d > $HOME/.kube/config

      - name: Deploy to K8S
        run: |
          helm delete services && helm install services k8s/services-chart
          sleep 60

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 5
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"